version: '3.7'

services:

  elasticsearch:
    image: elasticsearch:7.9.2
    #volumes:
      #- ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      #- elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
       ES_JAVA_OPTS: "-Xmx256m -Xms256m"
       discovery.type: single-node
       #ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
    networks:
      - elku
    
  kibana:
    image: kibana:7.9.2
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - "5601:5601"
    #environment:
      #KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - elku
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.9.2
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - "5000:5000/tcp"
      - "12201:12201/udp"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      #LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    networks:
      - elku
    depends_on:
      - elasticsearch

  heartbeat:
    build: 
      context: ./heartbeat
    container_name: heartbeat
    depends_on:
      - elasticsearch
      - kibana
      - logstash
    networks:
      - elku

networks:
  elku:
    driver: bridge

#volumes:
  #elasticsearch:
    #driver: local